GET http://localhost:3001/todos

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "build calorie app"
}
###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "DELETE THIS"
}

###
DELETE http://localhost:3001/todo/delete/636d5127b862c11ef50389ce

###
PUT http://localhost:3001/todo/complete/636d50eeb862c11ef50389cc